### ISSUE TITLE
Action buttons and checkbox unusable

### ISSUE THREAD

**Issue by jorgeneira** [ryanw3b3r/nova-clickable-row#1]
Hi,

I loved the idea behind the package, but I think there is problem with your implementation, out of the box this package makes buttons and checkboxes unusable, as it triggers the click event to edit/view no matter where you clicked, for example, if you select a row with checkbox, it also triggers the edit action.

**Comment by ryanw3b3r** [comment]
Hi, Thanks for your comment. I fixed it in version 0.1.2. Hopefully it's working now.

**Comment by ryanw3b3r** [comment]
Closing because it looks like it's fixed now. Feel free to reopen/comment if I'm wrong.

**Comment by MDobariya** [comment]
action buttons(delete, edit) are still not working if clickableRow event is set to click.

**Comment by ryanw3b3r** [comment]
Hi @MDobariya 

What OS and browser are you using? Is it the same in other browsers?

**Comment by ryanw3b3r** [comment]
@MDobariya this should be fixed in 0.1.3. Please update the package and let me know.

**Comment by ryanw3b3r** [comment]
Fixed. No feedback. Closing for now. Feel free to reopen/comment if I'm wrong.
